### ISSUE TITLE
Listing secret not capturing as a risky rule

### ISSUE THREAD

**Issue by prasenforu** [cyberark/KubiScan#10]
My RBAC (ServiceAccount,Role & RoleBinding) as follows, which has a role of listing secrets.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: listsecrets
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-list-secrets
rules:
- apiGroups: ["*"]
  resources: ["secrets"]
  verbs: ["list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-list-secrets
subjects:
- kind: ServiceAccount
  name: listsecrets
  namespace: testing
roleRef:
  kind: Role
  name: role-list-secrets
  apiGroup: rbac.authorization.k8s.io
```

![image](https://user-images.githubusercontent.com/19322497/62681676-e0139e00-b9d7-11e9-851e-c71ebded87af.png)

But **kubiscan -rr** does not capturing/show as a risky rule.

![image](https://user-images.githubusercontent.com/19322497/62681647-ce31fb00-b9d7-11e9-9c93-c4ce6f859ee9.png)

Not sure what is the criteria of risky rule?

**Comment by g3rzi** [comment]
Interesting, I will try to restore it on my machine and update you.
It is weird because it suppose to find it.

But I have two thoughts:
1. Maybe it is related to the context. When you run "kubectl get roles", can you see the role you created ? 
2. You didn't specify namespaces in the yaml file, so I suppose it will be automatically assigned to the default namespace but maybe kubiscan doesn't see the namespace and can't find it and do the correct compare.

**Comment by prasenforu** [comment]
I am using openshift, where I can set my namespace (```oc project <namespace>```)

Q. 2 -Ans.
so no need to specify namespace, its will take the namespace automatically. But it will NOT take ```default``` namespace.

Q. 1-Ans.

```
[root@ocpdns ocpscan]# oc get roles -n testing
NAME
role-list-secrets
```

**Comment by prasenforu** [comment]
As because its not capturing as a risky rule, associated serviceaccount mapped with POD also not showing as a ```risky pod```

```
apiVersion: v1
kind: Pod
metadata:
  name: pod-wo-sa
spec:
  automountServiceAccountToken: false
  serviceAccount: listsecrets
  containers:
    - name: pod-wo-sa
      image: bkimminich/juice-shop
      ports:
        - containerPort: 3000
```
![image](https://user-images.githubusercontent.com/19322497/62689939-5e2c7080-b9e9-11e9-89e6-2eb5213d012d.png)

**Comment by g3rzi** [comment]
I understand.
I didn't tested kubiscan on OpenShit, so this is why I didn't encounter it.
Can you show me the list of contexts you have in OpenShit?
Using "oc config get-contexts" ? 
I want to see what is the current context being used and the admin contexts.

**Comment by prasenforu** [comment]
```
CURRENT   NAME                                          CLUSTER            AUTHINFO                               NAMESPACE
          default/10-138-0-16:8443/admin                10-138-0-16:8443   admin/10-138-0-16:8443                 default
          default/cluster-1/admin                       cluster-1          admin/cluster-1                        default
          event-controller/10-138-0-16:8443/admin       10-138-0-16:8443   admin/10-138-0-16:8443                 event-controller
          heptio-ark/10-138-0-16:8443/admin             10-138-0-16:8443   admin/10-138-0-16:8443                 heptio-ark
          heptio-ark/10-138-0-17:8443/admin             10-138-0-17:8443   admin/10-138-0-17:8443                 heptio-ark
          kubewatch-kubewatch-10-138-0-16:8443          10-138-0-16:8443   kubewatch-kubewatch-10-138-0-16:8443   kubewatch
          kubewatch/10-138-0-16:8443/admin              10-138-0-16:8443   admin/10-138-0-16:8443                 kubewatch
          logging/10-138-0-16:8443/admin                10-138-0-16:8443   admin/10-138-0-16:8443                 logging
          loki/10-138-0-16:8443/admin                   10-138-0-16:8443   admin/10-138-0-16:8443                 loki
          loki/10-138-0-17:8443/admin                   10-138-0-17:8443   admin/10-138-0-17:8443                 loki
          ocp-view/10-138-0-16:8443/admin               10-138-0-16:8443   admin/10-138-0-16:8443                 ocp-view
          ocp-view/10-138-0-17:8443/admin               10-138-0-17:8443   admin/10-138-0-17:8443                 ocp-view
          ocpwatch/10-138-0-16:8443/admin               10-138-0-16:8443   admin/10-138-0-16:8443                 ocpwatch
          openshift-logging/10-138-0-16:8443/admin      10-138-0-16:8443   admin/10-138-0-16:8443                 openshift-logging
          openshift-monitoring/10-138-0-16:8443/admin   10-138-0-16:8443   admin/10-138-0-16:8443                 openshift-monitoring
          sample-app/10-138-0-16:8443/admin             10-138-0-16:8443   admin/10-138-0-16:8443                 sample-app
          sample-app/10-138-0-16:8443/pkar              10-138-0-16:8443   pkar/10-138-0-16:8443                  sample-app
          sample-app/10-138-0-17:8443/admin             10-138-0-17:8443   admin/10-138-0-17:8443                 sample-app
*         security/10-138-0-16:8443/admin               10-138-0-16:8443   admin/10-138-0-16:8443                 security
          security/10-138-0-16:8443/pkar                10-138-0-16:8443   pkar/10-138-0-16:8443                  security
          testing/10-138-0-16:8443/admin                10-138-0-16:8443   admin/10-138-0-16:8443                 testing
          testing/10-138-0-16:8443/pkar                 10-138-0-16:8443   pkar/10-138-0-16:8443                  testing

```

**Comment by prasenforu** [comment]
Please check the code , looks like its working with ```clusterrole```

**Comment by prasenforu** [comment]
Any update?

**Comment by g3rzi** [comment]
Please check now.
I noticed for an issue with the indents in the risky YAML file which didn't load the one of the risky roles.

**Comment by g3rzi** [comment]
By the way, can you add me on twitter @g3rzi  ? I would like to advise with you on other stuff related to Kubernetes.

**Comment by prasenforu** [comment]
OK, will add.

But I don't think issue was in your yaml, u fixed in your code.

Now with ```-rr``` its showing roles but its NOT capturing with ```-rp``` (risky pod)

**Comment by g3rzi** [comment]
There was an issue with the YAML which provides the roles you want it to capture. There was a wrong indent with one of the roles after the list secrets role which ignored the list secrets in the YAML when I load it. 

I will try to restore the `-rp` and then fix it.

**Comment by prasenforu** [comment]
If you saw my RBAC yaml top of discussion there was no issues.

**Comment by g3rzi** [comment]
I didn't speak about **your** RBAC yaml. I spoke about the `risky_roles.yaml`  that the KubiScan use to check for risky permissions. There an indent problem with it.

**Comment by prasenforu** [comment]
Oh! Sorry.

I am very sorry.

**Comment by g3rzi** [comment]
Its OK, don't worry :)

**Comment by prasenforu** [comment]
Let me know once it fix so I will close, it's a long discussion. :)

**Comment by g3rzi** [comment]
I tried to reproduce it with this YAML:
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: testing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: listsecrets
  namespace: testing
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-list-secrets
rules:
- apiGroups: ["*"]
  resources: ["secrets"]
  verbs: ["list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-list-secrets
subjects:
- kind: ServiceAccount
  name: listsecrets
  namespace: testing
roleRef:
  kind: Role
  name: role-list-secrets
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine3
  namespace: testing
spec:
  containers:
  - name: alpine3
    image: alpine3
    command: ["sleep 99d"]
  serviceAccountName: listsecrets
EOF
```

Notice that I have created a servuce account user named: `listsecrets` in the `testing` namespace.
I mounted this use to a pod inside the `testing` namespace.
With this YAML I can find the risky pod:  
![image](https://user-images.githubusercontent.com/11998736/63035219-6d1c9280-bec3-11e9-8a33-89f0680b52bf.png)  


When I used your YAML, I noticed that you didn't use the `testing` namespace:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: listsecrets
```  

For trobuleshooting, check with `-rs` that the use `listsecrets` exist in the risky subjects.
