### ISSUE TITLE
Issue in /KubiScan/engine/jwt_token.py

### ISSUE THREAD

**Issue by MMquant** [cyberark/KubiScan#59]
### Summary

I'm getting an error when running the kubiscan with `--kube-config` flag.
It seems that the issue is in `jwt_token.py` functions which (naturally) accept only JWT tokens.
I'm getting non-JWT tokens passed into the

```
def decode_jwt_token_data(jwt_token):
    splitted_string = jwt_token.split(".")
```

### Details

After running

`# kubiscan --kube-config "/root/.kube/config" -rp`

I get the stack trace

```
Traceback (most recent call last):
  File "/KubiScan/KubiScan.py", line 675, in <module>
    main()
  File "/KubiScan/KubiScan.py", line 606, in main
    print_all_risky_containers(priority=args.priority, namespace=args.namespace, read_token_from_container=args.deep)
  File "/KubiScan/KubiScan.py", line 141, in print_all_risky_containers
    pods = engine.utils.get_risky_pods(namespace, read_token_from_container)
  File "/KubiScan/engine/utils.py", line 435, in get_risky_pods
    risky_containers = get_risky_containers(pod, risky_users, deep_analysis)
  File "/KubiScan/engine/utils.py", line 348, in get_risky_containers
    risky_users_set = get_risky_users_from_container(container, risky_users, pod, volumes_dict)
  File "/KubiScan/engine/utils.py", line 380, in get_risky_users_from_container
    risky_user = get_jwt_and_decode(pod, risky_users, volumes_dict[volume_mount.name])
  File "/KubiScan/engine/utils.py", line 421, in get_jwt_and_decode
    decoded_data = decode_base64_jwt_token(secret.data['token'])
  File "/KubiScan/engine/jwt_token.py", line 7, in decode_base64_jwt_token
    return decode_jwt_token_data(decode_base64_bytes_to_string(decode_base64(base64_token)))
  File "/KubiScan/engine/jwt_token.py", line 13, in decode_jwt_token_data
    decoded_data_base64 = decode_base64(splitted_string[1])
IndexError: list index out of range
```

I echoed some values for debug purposes

```
[DEBUG] File /KubiScan/engine/utils.py, line 418, in get_jwt_and_decode
[DEBUG] secret: {'api_version': 'v1',
 'data': {'namespace': 'Yy1tLWR4YzI5N2s1',
          'token': '<base64-token>',
          'url': '<corp-url>'},
 'immutable': None,
 'kind': 'Secret',
 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"v1","data":{"namespace":"Yy1tLWR4YzI5N2s1","token":"<base64-token>","url":"<corp-url>"},"kind":"Secret","metadata":{"annotations":{},"name":"cattle-credentials-384a8b6","namespace":"cattle-system"},"type":"Opaque"}\n'},
              'creation_timestamp': datetime.datetime(2022, 11, 18, 8, 36, 9, tzinfo=tzlocal()),
...
...
...
```

The problem is that b64 decoded token in
```
'token': '<base64-token>',
```

doesn't contain 'dot', it doesn't seem to be a valid JWT token. It looks something like
```
msdtd24l2hg5vrzr8w9dnl897nkbfrbxd5sbljxg9hhbbwwkqr2cx2
```

When this data is passed to 

```
splitted_string = jwt_token.split(".")
```
then

```
splitted_string[1]
```

is empty and kubiscan throws an error.

Additionally the same .kubeconfig file works perfectly with kubectl CLI.

**Comment by g3rzi** [comment]
Thanks @MMquant , we will have a look at that and fix it.  
But how come the JWT doesn't contain a dot? the syntax is that it should have two dots for the separation.    

Another question for debugging, is your config file "/root/.kube/config" looks like that:  
```
apiVersion: v1
kind: Config
...
current-context: default-context
users:
- name: default-user
  user:
    token: <here_is_your_JWT_token>
```

If yes, are you using service account JWT token?

**Comment by MMquant** [comment]
The `config` looks as follows

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1USXlNVEU0TXpNMU1sb1hEVE15TVRJeE9ERTRNek0xTWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUjlKS29aSWh2Y05BUUVCQlFBRGdnRVBgRENDQVFvQ2dnRUJBTWkyCllOTVdnYmg1NzQwR3pGc1NBeW1hcEJJTXdtVk50VHB4TzRSTGNncmNKSHBkWU1oMHJIblhkZjIzbUppa21LV1UKV0dqYWpIb29yUmlSM1RRaDRHZU5scnJaS2kwbVV4OWtpYWwxYzF3U3l6T2hJQzNrR0trd3NLNlB3SzRPTjJzSAp4ZkJHQUdJS0NWb2YyM1JVRXFJOVlwR1liVDczNWg1WFVzYkZCa25KSDFsNUc1M253TjlTS3A5ekp4cGppcGJ0CmlPRU5ML0UyalVKRW05Znlzv2tZOWVRd2dpNG1tZ0owQWhCcFh1cVpXYTNhRjNSaW5MQ3dHbVIxcFhKNkRiaHIKM3ZPa1A0elBzVnh5SHRZZENKWkViZjFCd2l0QkJMNnVvVmlqS1pXL0xUdnNWdTZZYWlOY3RQbEdIeGh4TkttZgpqSGtyRGRBVkhZcEtPY2d3THVjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNVnVEOVk1ZFJVS2ZEdHFIZDRjUWlzM0RZeVBNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSHRFK0VyS1F2alFtRGNVR0J2YQp0c2ZRcnVoWWo3aGhLdzR3K05zUkZIWGg3MVBIM3BWelNRbnh2TVBQUTZEaGpTNmJHL29xN1BTdnNYg0h2ZnlJClFMZ2tvZ0M1dnI5UkRUcVhzVDkzK3VYb3N0ZHN5eEw5MklZUk5TbGhCQlMxaENJVWJiWVVpNXJ0a3FoQnpLN04KZGhncGZMU25NbkpieUNmYm1tQkNETHRuTldBZXRkYXBxdG9RbmNKaG12QkM2UlNwd2lVYnFYc1ZDcE5DYkdCZwpLQ3JWd1JKUExYbS9KQWppZDd3SGRhREtwT2tTMWd0U3byK0M1L3hPbzFUVlBrTlZZOHJoRkV3QTJjeUNtNS8vCjJ5U3k5b3dtNkhHQW5BV3VqNXhham5MekV5c2hLeTN4SVN4RlU3NmRoM3BzWTA2eXZwWW05NnUzdmMyTmpGM0kKUTlZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://<k8s-ip>:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJTzlyNnc1eHhyMzh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TWpFeU1qRXhPRE16TlRKYUZ3MHlNekV5TWpFeE9ETXpOVf5hTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTBUeTJ5RVRuNTJVUDlhNEoKV3o0a0hiYy81bHkrL2F5ai9NTVVRU1lQK3MyaEVaZEpRWDl3b3F5VXhzaFFaMG5iZk1PN3NkS0VhQlhxdWcxWQoyWjVkUHlzbW9xaEt4YVJtOGNpVXYxbUZFSlVDL2dlNVdDaVQzdkYxQkYvTFU0dnk5VDdXUmFUYm5WUFR4M3g4CmpLek5yU2dwV0Q1VzN1eHd0MU5WZUo1b0s0VHRNh1dkZVhxbTVpem9Pai9Pekc0MlFsNElsNGRWUG1Qb2U2Zk0KM29sZTR2am5TMkhWTTl5d3dPQjU5WnVZUFY5QjNkZmVaSC9mdGZsdFpaWU9IWEZndFBxV1NMSmRBOWtzTXh5NQpsQWhaNExXKy9kSEo0clI4SkVkRzNOcUJqR3lHWkN4ZW5wUzI3TDRINXIrZ3BWd21OVElLZm5BN3FNenZudnFUClVPZGRpd0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JURmJnL1dPWFVWQ253N2FoM2VIRUlyTncyTQpqekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbDU1SmJXditrdktZdGdZNlc5MUR5b0lrU0tJdTcwa2VJNVJPCnN1bENzMHRqckgxTm85NUJBU20yK3FSTklXM01XdkdfTkpVZzhPRlVVMG92TnlIQUwwdExCS2FCTDJrNHI2amEKbVR2ci9FaG1zTlVXU2cyYk5RMlJxVE9ISGw4SXBYWHlYMUIxNi90K0pLN0RaL2VxcFdZcFlXMVZUaHV3bzJoaQp1ZjQrU1dTV1pBdkxqMWVKVW1GVGt2d1BlQWkwNnZOeG9Gd2owc2g3UytaRjA5UDdHQ3hDS0lmSTQzbHV2OgJFCll3VmRtd2hJR0N5MHpVYjgwVWRpK3BBSm5aaWhlREhLdUZrVk5SZnBmK0IxaFNRN2E2aW0vMnE3VU0zajU1TVUKdlpCNVdVNzhFd2loT2I1WGtMbENSdFlOV0VqanhWMVlhOCs1OUNkQTBPY1R2SW1Zemc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMFR5MnlFVG41MlVQOWE0Sld6NGtIYmMvNWx5Ky9heWovTU1VUVNZUCtzMmhFWmRKClFYOXdvcXlVeHNoUVowbmJmTU83c2RLRWFCWHF1ZzFZMlo1ZFB5c21vcWhLeGFSbThjaVV2MW1GRUpVQy9nZTUKV0NpVDN2RjFCRi9MVTR2eTlUN1dSYVRiblZQVHgzeDhqS3pOclNncFdENVczdXh3dDFOVmVKNW9LNFR0TStXhAplWHFtNWl6b09qL096RzQyUWw0SWw0ZFZQbVBvZTZmTTNvbGU0dmpuUzJIVk05eXd3T0I1OVp1WVBWOUIzZGZlClpIL2Z0Zmx0WlpZT0hYRmd0UHFXU0xKZEE5a3NNeHk1bEFoWjRMVysvZEhKNHJSOEpFZEczTnFCakd5R1pDeGUKbnBTMjdMNEg1citncFZ3bU5USUtmbkE3cU16dm52cVRVT2RkaXdJREFRQUJBb0lCQUcwRU55L05SdzYzQjBPNApNOFBJY3NUUXo0aFUxbVlSWnpldzVJSzFOQ28yclM4ZkpkbnNibUV6amlpc0FjaHZJTjYybExxbnRya01na29CCjNrTTBVZDB4dkdXUFRiWUFYR3FwV1djQlcyVXlYbWJBMjM3bFZYWVpWQ0M5VUpEdEg5OUxxQlNOT3FlVUg0bVcKZ01aQzJyN1hhQU5FSjdycWNpZnlVVndSSExGZkZNQWQ2MFliVGxyelNMR3E3VGVRMk9icGhSWHAzT2l1QWcwMApJc0ZpUVBMQUpEdy9Fd3FxckxXcUozN3Q5aTh1MG1teTNwSXp3SEJINUorNwdyNExrVG92WEV6aHRYb3BJY3VCCkVIeTloS3pQOFBZaHRuV3RaS2pkZmREbmVHbEsrUmNSOGdkZ2U5ZytYUGxJeDB6N2hKZFJGQWREZE1DN0JEZksKYUxETjdlRUNnWUVBKzJROXhXZS9wUjZsblhGYzNBcFhTZ0RGbFZFMWxqTURBcDgySlFjaGVFdXdialljb3JNdwpZY3c1TDBwelA5N2x6dGFML2JBYlRJREpxQldoRElEaEU3YklrenJ6S0NjWDR0U0lWTWU4OTRYeWVKb2JCcXJjCjdlREJWUDVjcjFqVVlFeENlU0J1cU4zZ1d3MHZ5c1E3dEVxb1RrSXhVUXdVZEZGODdBcWVNWGtDZ1lFQTFSS2wKVUlUMVdNcEtTRTJ4OEpoanVJclBaNmlDd2NUMUwvZ3lmOWNDS1RmOE85OTEzK0tlYmFHNlQ1ZjRBb0NZSGJEMgp2TUZGU3JXY2lKcEw3TytLWWlibW5jTzBUWWQyVEwwSnhTOElaTGlma3l6clVFcFVgVDBMWStKQ3JGVzU3YXRGCmJlTWg0SmJvckFjZDUwSitsVS9RRysxZy82bTQrQ2ZDbUI3KzZpTUNnWUFVZU5oUzhCejZQR0d1VGFJTFJVaFEKZlhtWnJGQloxL09oemdkaHdvL21OUHU4TGVudEVmeVpxa0RwNmYweXNWc3ptZU15bUpuUWhCaG4rTUx4dXJrWgptdVFBb1dkVjJNRW9OcmlYZgVDYm82dllTR3gxQVlzV1VCeE9hSnh4cHlFOGFsbHJkY210Tk14bGZkQnJpY2wyCjZER0dsZnRnSjBTdktFZXREVHhPdVFLQmdRREkxZHRtcXZ4TFpkbGdqNE5TZ1lFMU4vbkkvZ2ZKdHVsWS9yd3kKemFubXlqT0JCOThtV1lmMVZFUzFzMHQ4cUZNNVlVMGdtNWZCbEs5bi91L2o4K0ZmSk1XcEhRZDlNRnJzZUI2VwpjditaV0lCcERDVDlPQ0w0bFRxQU9vdVh2dklTdUtZbnJyaUc1aGVIMXVsenlyUmY3cXY5TnVGLytpMDBFdDRUCjN0drVPd0tCZ1FEMXJxZWJTUWJzaEhkZkZhUXVLTkdadFFna1ZlVTMwdk1YMlA1dm9yUkFRU0FvaSt5QVE3T0UKVjMvUHprZ0RXSVIwZ2pXN3pWckxVWWZ5N1JuQnJTTXBzUDBQTkJkTmdPdEs4SVJQZXRqbkpyVnhOT2VPMFJ4WQpFK3QvVFdORE9vU0NEK2c2dnVsWHNhK1R6UW1NU0tGRWRmNkt1blpPZVVDZzB1aG5QRTB3UHc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
```

* data are modified, cert and privkey are isn't valid).
There are no JWT tokens in the `config` file. There are only certificates and RSA privkeys. 
What is interesting that the kubiscan doesn't work with our prod k8s cluster but it does with our testing cluster which 'should be' the exact copy and which has the same `config` file with certs and privkeys (it has just different cert and key).

I suspect that the issue is in some k8s component version.
